### ISSUE TITLE
Add podAnnotations section to helm chart

### ISSUE THREAD

**Issue by tommy-dk** [Comcast/kuberhealthy#115]
If a podAnnotations section is added to the helm chart, it is possible to add annotations to kuberhealthy which can be used for setting up external prometheus scrapers (eg datadog).

Eg:
```
  podAnnotations:
    ad.datadoghq.com/kuberhealthy.check_names: '["prometheus"]'
    ad.datadoghq.com/kuberhealthy.init_configs: '[{}]'
    ad.datadoghq.com/kuberhealthy.instances: '[{"prometheus_url":
      "http://%%host%%:8080/metrics", "namespace": "kuberhealthy", "metrics":
      ["kuberhealthy_*"]}]'
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
```
