### ISSUE TITLE
Make dependent images configurable

### ISSUE THREAD

**Issue by davidkarlsen** [Comcast/kuberhealthy#121]
**Describe the feature you would like and why you want it**
For closed corporate environments any images requested might need to go through an internal proxy, hence it would be good to be able configure the imagerepo/image required by kuberhealthy (like the gcr pause one).
The chart at https://github.com/helm/charts/tree/master/stable/kuberhealthy should take parameters to be able to point at these.

**Additional context**
See https://github.com/Comcast/kuberhealthy/issues/114 for background.

**Comment by lolimjake** [comment]
I've pushed an image tag for you to test with to  ds-image-override.  

I've added this feature as an argument `dsPauseContainerImageOverride` - If you add this argument to your running kuberhealthy deployment at `deployment.spec.template.spec.containers.args` you should be able to specify the location of the pause container image that the daemon set checker deploys.

Ex:

```
spec:
  template:
    spec:
      containers:
        args:
        - "-dsPauseContainerImageOverride"
        - "your-docker-repo/pause:0.8.0"
```

**Comment by davidkarlsen** [comment]
Which image tag should I use?

Small typo, should be
`"your-docker-repo/google_containers/pause:0.8.0"`

**Comment by davidkarlsen** [comment]
doh -  found it - ds-image-override

**Comment by davidkarlsen** [comment]
Sorry to disappoint:
```
kubectl -n kuberhealthy logs kuberhealthy-7fdc478568-pq7v7 
time="2019-02-25T23:02:04Z" level=info msg="Startup Arguments: [/app/kuberhealthy]"
time="2019-02-25T23:02:04Z" level=info msg="Starting web services on port :8080"
time="2019-02-25T23:07:24Z" level=info msg="I am now master. Starting checks."
time="2019-02-25T23:07:24Z" level=info msg="Became master. Starting checks."
time="2019-02-25T23:07:24Z" level=info msg="Running check: PodStatusChecker namespace kube-system"
time="2019-02-25T23:07:24Z" level=info msg="Running check: ComponentStatusChecker"
time="2019-02-25T23:07:24Z" level=info msg="Running check: DaemonSetChecker"
time="2019-02-25T23:07:24Z" level=info msg="Running check: PodRestartChecker namespace kube-system"
time="2019-02-25T23:07:24Z" level=info msg="Searching for unique taints on the cluster."
time="2019-02-25T23:07:24Z" level=info msg="Found taints to tolerate: [{dedicated  infra NoSchedule <nil>}]"
time="2019-02-25T23:07:24Z" level=info msg="Generating daemon set kubernetes spec."
time="2019-02-25T23:07:24Z" level=info msg="Deploying daemon set with tolerations:  [{dedicated  infra NoSchedule <nil>}]"
time="2019-02-25T23:07:24Z" level=info msg="Setting state of check ComponentStatusChecker to true []"
time="2019-02-25T23:07:24Z" level=error msg="Failed to create daemon set:Internal error occurred: admission webhook \"trust.hooks.securityenforcement.admission.cloud.ibm.com\" denied the request: \nDeny \"gcr.io/google_containers/pause:0.8.0\", no matching repositories in ClusterImagePolicy and no ImagePolicies in the \"kuberhealthy\" namespace"
time="2019-02-25T23:07:24Z" level=error msg="Something went wrong with daemonset deployment, cleaning things up..."
time="2019-02-25T23:07:24Z" level=info msg="DaemonSetChecker removing 0 daemonset pods"
time="2019-02-25T23:07:24Z" level=info msg="DaemonSetChecker removing daemonset"
time="2019-02-25T23:07:24Z" level=error msg="Failed to delete daemonset:daemonsets.extensions \"daemonset-test-kuberhealthy-7fdc478568-pq7v7-1551135724\" not found"
time="2019-02-25T23:07:24Z" level=info msg="Setting state of check PodRestartChecker namespace kube-system to true []"
time="2019-02-25T23:07:24Z" level=error msg="Error running check: DaemonSetChecker Internal error occurred: admission webhook \"trust.hooks.securityenforcement.admission.cloud.ibm.com\" denied the request: \nDeny \"gcr.io/google_containers/pause:0.8.0\", no matching repositories in ClusterImagePolicy and no ImagePolicies in the \"kuberhealthy\" namespace"
time="2019-02-25T23:07:24Z" level=info msg="Setting state of check PodStatusChecker namespace kube-system to true []"
time="2019-02-25T23:09:24Z" level=info msg="Running check: PodStatusChecker namespace kube-system"
time="2019-02-25T23:09:24Z" level=info msg="Running check: ComponentStatusChecker"
time="2019-02-25T23:09:24Z" level=info msg="Setting state of check ComponentStatusChecker to true []"
time="2019-02-25T23:09:24Z" level=info msg="Setting state of check PodStatusChecker namespace kube-system to true []"
```

pod:
```
...
containers:
  - args:
    - -dsPauseContainerImageOverride
    - fsnexus.evry.com:8085/google_containers/pause:0.8.0
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: fsnexus.evry.com:8085/comcast/kuberhealthy:ds-image-override
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
...
```
