### ISSUE TITLE
Failure to cleanup check pods when khcheck CRD is deleted during check run

### ISSUE THREAD

**Issue by jonnydawg** [Comcast/kuberhealthy#200]
**Describe the bug**
External check pods created during check runs are not cleaned up if the khcheck is deleted.

**Steps To Reproduce**
Add a khcheck
```yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: my-external-check
  namespace: kube-system
spec:
  runInterval: 30s
  metadata:
      annotations:
        iam.amazonaws.com/role: <aws-arn>
  podSpec:
    containers:
    - name: my-external-check
      image: <image>
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 15m
          memory: 50Mi
```
Wait for the external check to run, and delete the khcheck before the run completes and reports back.
```
kubectl delete khcheck my-external-check
```
Observe that the pod remains.

**Expected behavior**
The master should clean up dead external checks.
