### ISSUE TITLE
Deployment check failed to report status

### ISSUE THREAD

**Issue by omerlh** [Comcast/kuberhealthy#334]
**Describe the bug**
 level=fatal msg="error reporting to kuberhealthy: bad status code from kuberhealthy status reporting url: %!s(int=400)%!(EXTRA string=400 Bad Request)"

**Steps To Reproduce**
- Create a deployment check that failed (e.g. with missing RBAC permissions)

```yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment-check
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    containers:
    - name: deployment
      image: quay.io/comcast/deployment-check:1.1.0
      imagePullPolicy: IfNotPresent
      env:
        - name: CHECK_IMAGE
          value: "nginx:1.17-perl"
        - name: CHECK_IMAGE_ROLL_TO
          value: "nginx:1.17.5-perl"
        - name: CHECK_DEPLOYMENT_REPLICAS
          value: "4"
        - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
          value: "true"
      resources:
        requests:
          cpu: 15m
          memory: 15Mi
        limits:
          cpu: 25m
      restartPolicy: Always
```

**Expected behavior**
The check is able to report the status on failure

**Versions**
 - Kubernetes Version: 1.14
 - Kuberhealthy Release or build 2.1.0
