### ISSUE TITLE
allow negative tests

### ISSUE THREAD

**Issue by bavarianbidi** [Comcast/kuberhealthy#431]
**Describe the feature you would like and why you want it**

During cluster-provisioning/cluster-updates we trigger some tests in each cluster to verify the applied configuration.

In one of these tests we ensure, that Openstacks metadata-API endpoint isn't reachable from within a `pod`. Therefore we use [goss](https://github.com/aelsabbahy/goss) with this configuration-block:

```
    addr:
      tcp://169.254.169.254:80:
        reachable: false
        timeout: 500
``` 

We started the migration of these permanent tests to kuberhealthy and got the first success with most tests where we expect a success.

It would be nice if it's possible to define (via `ENV_VAR`) if a test is a positive or negative test.

We would contribute such a flag (in the corresponding check-command) if this request is valid ;-)
