### ISSUE TITLE
KH_EXTERNAL_REPORTING_URL not respected

### ISSUE THREAD

**Issue by davidkarlsen** [Comcast/kuberhealthy#715]
**Describe the bug**

When overriding KH_EXTERNAL_REPORTING_URL through env-var it is not used by kh:

`k logs kuberhealthy-57f6557465-dsvhb |grep svc`:
```
time="2020-10-28T00:04:53Z" level=info msg="External check reporting URL set to: http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus"
```

`k get pod kuberhealthy-57f6557465-dsvhb -o yaml`:
```
...
spec:
  automountServiceAccountToken: true
  containers:
  - args:
    - -dsPauseContainerImageOverride
    - fsnexus.evry.com:8085/google_containers/pause:3.1
    command:
    - /app/kuberhealthy
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: KH_EXTERNAL_REPORTING_URL
      value: http://kuberhealthy.kuberhealthy.svc.icp-global.local/externalCheckStatus
    image: fsnexus.evry.com:8085/kuberhealthy/kuberhealthy:v2.3.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
```

**Steps To Reproduce**
Install chart v32 with values:
```
    image:
      repository: fsnexus.evry.com:8085/kuberhealthy/kuberhealthy
    prometheus:
      enabled: true
    deployment:
      env:
        KH_EXTERNAL_REPORTING_URL: http://kuberhealthy.kuberhealthy.svc.icp-global.local/externalCheckStatus
      nodeSelector:
        fs.evry.com/finods-group: aot
      args:
      - -dsPauseContainerImageOverride
      - fsnexus.evry.com:8085/google_containers/pause:3.1
    podSecurityPolicy:
      enabled: true
    check:
      daemonset:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/daemonset-check
        extraEnvs:
          PAUSE_CONTAINER_IMAGE: "fsnexus.evry.com:8085/google-containers/pause:3.1"
      deployment:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/deployment-check
        extraEnvs:
          PAUSE_CONTAINER_IMAGE: "fsnexus.evry.com:8085/google-containers/pause:3.1"
          CHECK_IMAGE: "fsnexus.evry.com:8085/nginxinc/nginx-unprivileged:1.17.8"
          CHECK_IMAGE_ROLL_TO: "fsnexus.evry.com:8085/nginxinc/nginx-unprivileged:1.17.9"
          CHECK_CONTAINER_PORT: "8080"
      dnsInternal:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/dns-resolution-check
      dnsExternal:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/dns-resolution-check
      podRestarts:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/pod-restarts-check
      podStatus:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/pod-status-check
      networkConnection:
        image:
          repository: fsnexus.evry.com:8085/kuberhealthy/network-connection-check
    checkReaper:
      image:
        repository: fsnexus.evry.com:8085/kuberhealthy/check-reaper
```

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can paste images into github and they will upload automatically.

**Versions**
 - Cluster OS: [e.g. CoreOS 1800.1.0]
 - Kubernetes Version: 1.9.7
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235]

**Additional context**
KH will read the value from the configmap - but that's not configurable through helm.
