### ISSUE TITLE
Helm: ServiceMonitor Endpoints specifications should be parametrised

### ISSUE THREAD

**Issue by geoL86** [Comcast/kuberhealthy#726]
Hi,

ServiceMonitor contains specifications for Endpoints with bearerTokenFile by default:

https://github.com/Comcast/kuberhealthy/blob/master/deploy/helm/kuberhealthy/templates/servicemonitor.yaml

```
  endpoints:
  - port: http
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

For example on OpenShift 4.5 (may be and for higher versions) this leads to errors on the Prometheus Operator:
```
level=warn ts=2020-11-17T13:10:45.207565415Z caller=operator.go:1803 component=prometheusoperator msg="skipping servicemonitor" error="it accesses file system via bearer token file which Prometheus specification prohibits" servicemonitor=kuberhealthy/kuberhealthy namespace=openshift-user-workload-monitoring prometheus=user-workload
```
As result scrape configuration isn't available as well as metrics.
