### ISSUE TITLE
storage-check-pvc-init-job constantly failing

### ISSUE THREAD

**Issue by ElectricRabbit** [Comcast/kuberhealthy#733]
Hello, 
I'd like to ask about storage check job, I'm only getting **/bin/sh: 1: cannot create /data/index.html: Permission denied** using storage-check-pvc-init-job. I've just tried to enable allowPrivilegeEscalation and it did't help. Normally we have no problem to write to PVs. I'm thinking about **securityContext.readOnlyRootFilesystem**, but this swich is quite dangerous for production as it is global switch.
Is it possible, that this test is not compatible with old StorageClass we are still using?

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

What Am I missing?

EDIT: nope, not working even with `securityContext.readOnlyRootFilesystem=false`
