### ISSUE TITLE
REQ: Global image prefix

### ISSUE THREAD

**Issue by TJM** [Comcast/kuberhealthy#734]
**Describe the feature you would like and why you want it**
Due to the rate limiting that docker.io has implemented, I would like to be able to add a prefix to all docker images that kuberhealthy runs. I could modify several images, but I would like a "global" setting where I could prefix all images with something like artifactory.company.com.

**Additional context**
Thanks in advance!?

**Comment by TJM** [comment]
Actually, if we could split the image registry from the repository like this:

```yaml
image:
  registry: docker.io
  repository: kuberhealthy/kuberhealthy
  tag: 2.3.1
```

.. that would probably simplify adding a global override:
```yaml
global:
  imageRegistry: artifactory.company.com
```
