### ISSUE TITLE
enhance http-check: add support for other request types apart from GET and configurable expected status code

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [Comcast/kuberhealthy#779]
**Describe the feature you would like and why you want it**
As of now, the http-check is capable of only performing GET requests. But there are many possibilities for synthetic monitoring checks which rely on other request types like POST/PUT/etc.. For example, a synthetic monitoring check which performs a dummy upload of a k-v pair to a consul endpoint relies on a POST request. 
Also, a configurable expected status code instead just checking for `200` status would be much better in this situation. For example, many API calls conventionally respond with a 201 or 204 on a successful POST or PUT response.

The env vars `REQUEST_TYPE`, `REQUEST_BODY` and `EXPECTED_STATUS_CODE` can define the request type, request body and the expected status code from the response respectively. 
Something like this.
```yaml
name: CHECK_URL
value: https://my-sample-website.com
name: REQUEST_TYPE
value: "POST"
name: REQUEST_BODY
value: '{"email": "alex@mail.com", "password": "H3LL0"}'
name: EXPECTED_STATUS_CODE
value: "201"
```

**Additional context**
For ensuring backwards compatibility to the current version, we can make sure that the default `REQUEST_TYPE` is "GET".
